#!/bin/bash

#info#
tput smso;
echo "  __  __   _  __  ____       _      ____    _   _ ";
echo " |  \/  | | |/ / | __ )     / \    / ___|  | | | |";
echo " | |\/| | | ' /  |  _ \    / _ \   \___ \  | |_| |";
echo " | |  | | | . \  | |_) |  / ___ \   ___) | |  _  |";
echo " |_|  |_| |_|\_\ |____/  /_/   \_\ |____/  |_| |_|";
echo "                                                  ";
tput rmso;
echo "-This script simplifies making commands for executing scripts-"
echo "Code by Inbell1s"
echo
echo

while true; do
        if [ -f /bin/sbash ]
                then
                break
        else
echo "#!/bin/bash

tput smso;
echo "List of all mkbash commands:"
echo
tput rmso
basename -a $(grep -rwlh "##mkbcf##" /bin)
echo" > /bin/sbash
chmod +x /bin/sbash
 fi
done

while true; do
	if [ -f /var/log/mkbash.log ]
 		then
  		break
	else
  		 > /var/log/mkbash.log
	tput smso;
		echo "Log created."
	tput rmso;
	echo
 fi
done
tput smso;
echo "Options:"
PS3='
What would you like to do?:'
options=("Create" "Edit" "Remove" "List" "Show command" "Quit")
tput rmso;
select opt in "${options[@]}"
do
    case $opt in
        "Create")
		tput smso;
		echo "Command Creation"
		echo
		echo "Specify the desired command name, path to script and prefix if needed"
		tput rmso;
		echo
		echo "Command name:"
		read Name
		echo
		echo "Path to script:"
		read Command
		echo
		echo "Prefix (if desired):"
		read Prefix
	
#Input validation#

while true; do
	if command -v $Name >/dev/null 2>&1
 		then
  		tput smso;
  		echo "Command already exists, please use another name."
  		tput rmso;
  		echo "New command name:"
  		read Name
	else
  		break
	fi
done

while true; do
if [ -f "$Command" ]
 then
  break
 else
  tput smso;
  echo "Script file does not exist, please check your path."
  tput rmso;
  echo "New script path:"
  read Command
fi
done

#Create command file#

echo '#!/bin/bash
##mkbcf##
'$Prefix' '$Command' "$@"' > /bin/"$Name"

chmod +x /bin/"$Name"

#Add command to log file #

echo "'$Name' - '$Prefix' '$Command'" >> /var/log/mkbash.log

tput setaf 2;
tput bold;

#Finishing#

echo
echo
echo 'Creation complete, testing the command using "'"$Name"'"'

tput sgr0;

sleep 4

"$Name"
            ;;
        "Edit")
		tput smso;
		echo "Edit existing command, please specify old name and new name:"
		tput rmso;
		echo
                echo "Old command name:"
                read oldname
                echo
                echo "New command name:"
                read newname
      while true; do
     if grep -q "##mkbcf##" /bin/$oldname > /dev/null 
                then
		mv /bin/"$oldname" /bin/"$newname"
                tput smso;
                echo "Command changed from "$oldname" to "$newname"."
                tput rmso;
		sed -i "s/'$oldname'/'$newname'/g" /var/log/mkbash.log
                sleep 5
		exit
        else
                tput smso;
		echo "Command does not exist/is not a mkbash command, please use a valid command."
		tput rmso
		basename -a $(grep -qrwlh "##mkbcf##" /bin)
		echo
		echo "Old command:"
		read oldname
        fi
done

            ;;


        "Remove")
	tput smso;
            echo "Remove existing command."
	    echo
        tput rmso;	
	    echo "Name of the command you wish to delete:"
	    read delete
	
while true; do
      if grep-q "##mkbcf##" /bin/$delete > /dev/null 
                then
                rm /bin/"$delete"
                tput smso;
                echo "Command "$delete" removed."
                tput rmso;
                sed -i "/'$delete'/d" /var/log/mkbash.log
                sleep 5
                exit
else
                tput smso;
                echo "Command does not exist/is not a mkbash command, please use a valid command."
                tput rmso
                basename -a $(grep -rwlh "##mkbcf##" /bin)
                echo
                echo "Command you wish to delete:"
                read delete

fi
done
            ;;
"List")
        tput smso;
            echo "List of all created commands:"
            echo
        tput rmso;      
            basename -a $(grep -rwlh "##mkbcf##" /bin)
            echo
            ;;
            
            "Show command")
            tput smso;
            echo "Choose the command you want to view:"
            tput rmso;
            echo
            basename -a $(grep -rwlh "##mkbcf##" /bin)
            echo
            echo "Command name:"
            read show
            echo
            echo
 while true; do
        if grep -q "##mkbcf##" /bin/$show > /dev/null 
	  then
            cat /bin/$show
	break
else
                tput smso;
                echo "Command does not exist/is not a mkbash command, please use a valid command."
                tput rmso
echo
echo "Available commands:"
                basename -a $(grep -rwlh "##mkbcf##" /bin)
                echo
                echo "Command you wish to show:"
                read show

fi
done
            ;;
            

        "Quit")
            exit
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
 
